version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 99
