"""Constants for the test suite fixtures."""
TEST_LOCALE = "fr_FR"
TEST_ACCOUNT_ID = "account-id-1"
TEST_COUNTRY = "FR"
TEST_USERNAME = "test@example.com"
TEST_PASSWORD = "test_password"
TEST_PERSON_ID = "person-id-1"
TEST_GIGYA_URL = "https://accounts.eu1.gigya.com"
TEST_KAMEREON_URL = "https://api-wired-prod-1-euw1.wrd-aws.com"
TEST_VIN = "VF1AAAAA555777999"
