name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

permissions:
  contents: read

env:
  DEFAULT_PYTHON: "3.14"

jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/renault-api
    permissions:
      # Needed to attest the SBOM against the built artifacts
      attestations: write
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          version: "0.12.22"
          python-version: ${{ env.DEFAULT_PYTHON }}
          # No cache on release builds, to avoid cache poisoning
          enable-cache: false

      - name: Set package version
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          version="${RELEASE_TAG,,}"
          version="${version#v}"
          uv version "${version}" --frozen

      - name: Build package
        run: |
          uv build

      - name: Locate built wheel
        run: |
          WHEEL_PATH=$(ls dist/renault_api-*-py3-none-any.whl)
          echo "WHEEL_PATH=${WHEEL_PATH}" >> "${GITHUB_ENV}"

      - name: Generate CycloneDX SBOM
        uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          file: ${{ env.WHEEL_PATH }}
          format: cyclonedx-json
          output-file: renault-api.cdx.json
          upload-artifact: false
          upload-release-assets: false

      - name: Attest SBOM against built artifacts
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: "dist/*"
          sbom-path: renault-api.cdx.json

      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          verbose: true
          print-hash: true
