name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-release-draft:
    name: Draft release
    runs-on: ubuntu-latest
    permissions:
      # Needed to create and update the draft release
      contents: write
      # Needed to read merged pull requests and their labels
      pull-requests: read
    steps:
      - name: Draft release notes
        uses: release-drafter/release-drafter@72967cdc98ddd3160f1fc3dff619de365e137dd0 # v7.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
